---
title: "Correlation and Association"
---


```{r include=FALSE, results="asis"}
echo_boot <- FALSE
echo_pformat <- FALSE
if (exists("df_num")){
  if (ncol(df_num)>0L & nrow(df_num)>=5){
    if (sum(rateunique_df) >= 2L){
echo_boot <- (count_pearsoncorr>0)
echo_pformat <- (count_pformat>0)
}}}
```

```{whites, eval=FALSE, echo = echo_boot}
# Function for the bootstrap confidence interval
pearsoncorr <- function(data,i){
  d <- data[i, ]
  return(cor(d, use="complete.obs", method="pearson")[1,2])
}
```

```{whites, eval=FALSE, echo = echo_pformat}
# Function for the p-value format:
pformat<-function(p){
  if (p<0.001) return("<0.001") else return (round(p,3))
}
```

```{r, results="asis"}

options(na.action=na.omit)

if (exists("df_num")){
  
  if (ncol(df_num)>0L & nrow(df_num)>=5){
    
    if (sum(rateunique_df) >= 2L){
      
      combs = combn(c(1:(ncol(df_num))),2)
      
      # Initialize refs as FALSE
      count_lin <- 0
      count_interpretp <- 0
      trace(linearity,tracer=function() {count_lin <<- count_lin + 1},print=FALSE)
      trace(interpret_p,tracer=function() {count_interpretp <<- count_interpretp + 1},print=FALSE)
      
      for (s in 1:16){
        name2 <- paste("refs",s,sep="")
        assign(name2,FALSE)
      }
      
      # Analysis for each pair 
      for (i in 1:ncol(combs)){
        
        j = combs[1,i]
        k = combs[2,i]
        
        # Initialize outputs as FALSE
        for (s in 1:16){
          name <- paste("output",s,sep="")
          assign(name,FALSE)
        }
        
        
        # Define rate of unique values to control continuity 
        rateunique1 <- length(unique(df_num[,j])) / nrow(df_num)
        rateunique2 <- length(unique(df_num[,k])) / nrow(df_num)
        
        
        # Consider bivariate continuous 
        if (rateunique1 >= cutoffcont(nrow(df_num)) & rateunique2 >= cutoffcont(nrow(df_num))){
          
          a <- which(colnames(df2)==colnames(df_num)[j])
          b <- which(colnames(df2)==colnames(df_num)[k])
          
          cat("\\# `Columns:",colnames(df_num)[j],"and",colnames(df_num)[k],"`")
          cat("\\newline ")                                                                          
          cat("`j = `",a)
          cat("\\newline ")                                                                                                    
          cat("`k =`",b)
          cat("\\newline ")                                                                                                        
          
          tryCatch({
            # Define check function for Pearson
            check <- linearity(df_num[,j],df_num[,k])
          }, error=function(e){cat("")})     
          
          
          tryCatch({
            # Define check function for Spearman & Kendall 
            checkm <- linearity(rank(df_num[,j]),rank(df_num[,k]))
          }, error=function(e){cat("")})    
          
          
          tryCatch({
            pcorrelation <- cor(df_num[,j],df_num[,k], use="complete.obs", method="pearson")
          }, error=function(e){cat("")})    
          
          
          
          tryCatch({
            spcorrelation <- cor(df_num[,j],df_num[,k], use="complete.obs", method="spearman")
          }, error=function(e){cat("")})   
          
          
          tryCatch({
            ken <- cor(df_num[,j],df_num[,k], use="complete.obs", method="kendall")
          }, error=function(e){cat("")}) 
          
          
          tryCatch({  
            if (check==TRUE & exists("pcorrelation")) {
              cat("`pcorrelation <- cor(df[,j],df[,k], use=\"complete.obs\", method=\"pearson\")`")
              cat("\\newline ") 
              cat("`round(pcorrelation,4)` # `Pearson correlation coefficient`")
              cat("\\newline ")
              cat("\\newline ")
            }
          }, error=function(e){}) 
          
          
          tryCatch({  
            if (check==TRUE & normality(df_num[,j],df_num[,k])==TRUE) {
              cat("`fisherci <- cor.test(df[,j],df[,k], method=\"pearson\")`")
              cat("\\newline ")
              cat("`c(round(fisherci$conf.int[1],4),round(fisherci$conf.int[2],4))` # `confidence interval`")
              cat("\\newline ")
              cat("`pformat(fisherci$p.value)` # `p-value`")
              cat("\\newline ")
              cat("\\newline ")
                
            }
          }, error=function(e){cat("")}) 
          
          
          tryCatch({  
            if (check==TRUE & normality(df_num[,j],df_num[,k])==FALSE & nrow(df_num) < 800) {
              temp <- data.frame(df_num[,j],df_num[,k])
              bootdata <- boot(temp, statistic=pearsoncorr, R=1000)
              if (length(unique(round(bootdata$t,2)))>1){
                
                cat("`temp <- data.frame(df[,j],df[,k])`")
                cat("\\newline ")
                cat("`bootdata <- boot(temp, statistic=pearsoncorr, R=1000)`")
                cat("\\newline ")
                cat("`bootresult <- boot.ci(bootdata, type=\"bca\")`")
                cat("\\newline ")
                cat("`c(round(bootresult$bca[4],4),round(bootresult$bca[5],4))` # `bootstrap conf. interval`")
                cat("\\newline ")
                cat("\\newline ")
              
                }}
              
          }, error=function(e){cat("")}) 
          
          
          tryCatch({  
            if ((check==TRUE & normality(df_num[,j],df_num[,k])==FALSE & exists("spearman")) || (check==FALSE & checkm==TRUE & exists("spearman")))   {
              
              cat("`spcorrelation <- cor(df[,j],df[,k], use=\"complete.obs\", method=\"spearman\")`")
              cat("\\newline ") 
              cat("`round(spcorrelation,4)` # `Spearman correlation coefficient`")
              cat("\\newline ")
              cat("\\newline ")
            }
          }, error=function(e){cat("")}) 
          
          
          tryCatch({ 
          if ((check==TRUE & normality(df_num[,j],df_num[,k])==FALSE & exists("spearman")) || (check==FALSE & checkm==TRUE & exists("spearman")))   {

              spearmanci <- SpearmanRho(df_num[,j],df_num[,k], use="complete.obs", conf.level=0.95)
              spearmanci2 <- cor.test(df_num[,j],df_num[,k], method="spearman", exact=TRUE)
                 
              cat("`spearmanci <- SpearmanRho(df[,j],df[,k], use=\"complete.obs\", conf.level=0.95)`")
              cat("\\newline ") 
              cat("`c(round(spearmanci[2],4),round(spearmanci[3],4))` # `confidence interval`")
              cat("\\newline ") 

              cat("`spearmanci2 <- suppressWarnings(cor.test(df[,j],df[,k], method=\"spearman\", exact=TRUE))`")
              cat("\\newline ") 
              cat("`pformat(spearmanci2$p.value)` # `p-value`")
              cat("\\newline ") 
              cat("\\newline ") 
              
            }
          }, error=function(e){cat("")}) 
          
          
           tryCatch({  
           if ((check==TRUE & normality(df_num[,j],df_num[,k])==FALSE) || (check==FALSE & checkm==TRUE)) {
             
              cat("`ken <- cor(df[,j],df[,k], use=\"complete.obs\", method=\"kendall\")`")
              cat("\\newline ") 
              cat("`round(ken,4)` # `Kendall's tau correlation coefficient`")
              cat("\\newline ")
              cat("\\newline ")
            }
          }, error=function(e){cat("")}) 
          
          
           tryCatch({ 
            if ((check==TRUE & normality(df_num[,j],df_num[,k])==FALSE) || (check==FALSE & checkm==TRUE)) {
              kentest <- cor.test(df_num[,j],df_num[,k], method="kendall")
             
               cat("`kentest <- cor.test(df[,j],df[,k], method=\"kendall\")`")
              cat("\\newline ")
              cat("`pformat(kentest$p.value)` # `p-value`")
              cat("\\newline ")
              cat("\\newline ")
              }
            }, error=function(e){cat("")}) 
          
          
           tryCatch({ 
            
            if (check==FALSE & checkm==FALSE){
             
              tryCatch({ 
                
                if (nrow(df_num) <= 100){
                  mic <- testforDEP(df_num[,j],df_num[,k], test="MIC", rm.na=TRUE, p.opt="MC")
                } else {mic <- testforDEP(df_num[,j],df_num[,k], test="MIC", rm.na=TRUE, p.opt="table")}
  
                cat("`if (nrow(df) <= 100){`")
                cat("\\newline ")
                cat("`mic <- testforDEP(df[,j],df[,k], test=\"MIC\", rm.na=TRUE, p.opt=\"MC\")`")
                cat("\\newline ")
                cat("`} else {mic <- testforDEP(df[,j],df[,k], test=\"MIC\", rm.na=TRUE, p.opt=\"table\")}`")
                cat("\\newline ")
                cat("`micval <- minerva::mine(df[,j],df[,k], na.rm=TRUE)$MIC`")
                cat("\\newline ")
                cat("`round(micval,3)`     # `Maximal Information Coefficient (MIC)`")
                cat("\\newline ")
                cat("`pformat(mic@p_value)` # `p-value MIC`")
                cat("\\newline ")
                cat("\\newline ")
              
              }, error=function(e){cat("")}
              ) 
              
              tryCatch({ 
                
                 temp <- data.frame(df_num[,j],df_num[,k])
                 temp2 <- temp[complete.cases(temp),]
                 dist <- dcor.test(temp2[,1],temp2[,2], R=100)
                 
                 cat("`temp <- data.frame(df[,j],df[,k])`")
                 cat("\\newline ")
                 cat("`temp2 <- temp[complete.cases(temp),]`")
                 cat("\\newline ")
                 cat("`dist <- dcor.test(temp2[,1],temp2[,2], R=100)`")
                 cat("\\newline ")
                 cat("`round(dist$statistic,3)`  # `Distance correlation coefficient`")
                 cat("\\newline ")
                 cat("`pformat(dist$p.value)` # `p-value`")
                 cat("\\newline ")
                 cat("\\newline ")
               
              }, error=function(e){cat("")}) 
              
            }

          }, error=function(e){cat("")}) 
          
          

            cat("`scatterplotMatrix(~df[,j]+df[,k], smooth=FALSE, var.labels=colnames(df)[c(j,k)],`")
            cat("\\newline ")
            cat("`main=\"Enhanced Scatterplots\", col = \"`#`2fa42d\")`")
            cat("\\newline ")
            cat("\\newline ")
           
          
}}}}}
  
cat("\\pagebreak")
        
```
